version: '3'

services:

  webrise_db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webrise_service_db
    networks:
      - webrise_network

  webrise-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - webrise_db
    ports:
      - "8080:8080"
    networks:
      - webrise_network

networks:
  webrise_network:
    driver: bridge