
spring:
  application:
    name: webrise-service

  jpa:
    hibernate:
      show_sql: true
      ddl_auto: create

  datasource:
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://webrise_db/webrise_service_db


